apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-service
  annotations:
    prometheus.io/path: /actuator/prometheus                                                                                                                                                                                                                                 │
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 9005
    protocol: TCP
  selector:
    app: account-service
